SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/CourseList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using QuizSystem.Models;

namespace QuizSystem.Pages.ClassManagement
{
    public class CourseListModel : PageModel
    {
        private readonly QuizSystem.Models.OnlineQuizContext _context;

        public CourseListModel(QuizSystem.Models.OnlineQuizContext context)
        {
            _context = context;
        }

        public IList<Course> Course { get;set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.Courses != null)
            {
                Course = await _context.Courses.ToListAsync();
            }
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using QuizSystem.Models;

namespace QuizSystem.Pages.ClassManagement
{
    public class DetailsModel : PageModel
    {
        private readonly QuizSystem.Models.OnlineQuizContext _context;

        public DetailsModel(QuizSystem.Models.OnlineQuizContext context)
        {
            _context = context;
        }

      public Class Class { get; set; } = default!;
        public IList<TakeClass> TakeClass { get; set; } = default!;

        public ActionResult OnGet(int? id)
        {
            return startUp(id);

        }
        private ActionResult startUp(int? id)
        {
            Class = _context.Classes.Include(x => x.Course)
                .Include(x => x.LecturerAccountNavigation).Include(x => x.CoWorkerNavigation).SingleOrDefault(x => x.ClassId == id);
            if (Class != null)
            {
                TakeClass = _context.TakeClasses.Include(x => x.StudentAccountNavigation).Where(x => x.ClassId == id).ToList();

                return Page();
            }
            else
            {
                return RedirectToPage("/Courses/ManageCourses");
            }

        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QuizSystem.Models;

namespace QuizSystem.Pages.ClassManagement
{
    public class EditModel : PageModel
    {
        private readonly QuizSystem.Models.OnlineQuizContext _context;

        public EditModel(QuizSystem.Models.OnlineQuizContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Class Class { get; set; } = default!;
        public IList<Lecturer> Lecturers { get; set; } = default!;
        public IList<Course> Courses { get; set; } = default!;
        public IList<TakeClass> TakeClass { get; set; } = default!;
        public IList<Student> Students { get; set; } = default!;

        public IList<Student> StudentsNotAttend { get; set; } = default!;

        public ActionResult OnGet(int? id)
        {
            return startUp(id);
            /*Lecturers = await _context.Lecturers
                .Include(x => x.AccountNavigation).Where(c=>c.Account != Class.LecturerAccount && c.Account != Class.CoWorker).ToListAsync();
            Courses = await _context.Courses.ToListAsync();
            Students = await _context.Students
                .Include(x => x.AccountNavigation).ToListAsync();
            TakeClass = mySystem.TakeClasses.Include(x => x.StudentAccountNavigation).Where(x => x.ClassId == id).ToList();

            List<Class> listClass = mySystem.Classes.Include(x => x.Course).Where(x=>x.EndDate >= DateTime.Today).ToList();
            List<Student> s = new List<Student>();
            foreach (var item in Students)
            {
                using (var context = new OnlineQuizContext())
                {
                    int count = 0;
                    TakeClass t1 = new TakeClass();
                    foreach (var c in listClass)
                    {
                        t1 = mySystem.TakeClasses.Include(x => x.StudentAccountNavigation).SingleOrDefault(x => x.StudentAccount == item.Account && x.ClassId == c.ClassId && x.Class.CourseId == Class.CourseId);
                        if(t1 != null)
                        {
                            count++;
                        }
                    }
                    if (count == 0)
                    {
                        s.Add(item);
                    }
                }
            }
            StudentsNotAttend = s;*/
        }
        public async Task<IActionResult> OnPostAsync(string id, string name, string startdate, string enddate )
        {
            var mySystem = new OnlineQuizContext();
            var _c = mySystem.Classes.SingleOrDefault(x => x.ClassName == name && x.ClassId != Int32.Parse(id));
            if (String.IsNullOrEmpty(name))
            {
                TempData["FailMessage"] = "Class name is only contains alphabet, numbers and hyphen(ABC-123).";
            }
            else if (!IsAlphaNumericWithHyphen(name))
            {
                TempData["FailMessage"] = "Class name is only contains alphabet, numbers and hyphen(ABC-123).";
            }
            else if (DateTime.Parse(startdate) > DateTime.Parse(enddate))
            {
                TempData["FailMessage"] = "Start date cannot be earlier than end date.";
            }
            else if (_c != null)
            {
                TempData["FailMessage"] = "ClassName already exist!";
            }
            else if (_c == null)
            {
                using (var context = new OnlineQuizContext())
                {
                    Class c = context.Classes.Include(x => x.Course)
                        .Include(x => x.LecturerAccountNavigation).SingleOrDefault(x => x.ClassId == Int32.Parse(id));
                    c.ClassName = name;
                    c.StartDate = DateTime.Parse(startdate);
                    c.EndDate = DateTime.Parse(enddate);
                    context.Entry<Class>(c).State =
                        Microsoft.EntityFrameworkCore.EntityState.Modified;
                    context.SaveChanges();
                }
                TempData["SuccessMessage"] = "Update Class Information Successfully!";
                return RedirectToPage("./Edit", new { id = id });
            }
            return RedirectToPage("./Edit", new { id = id });
        }

        public IActionResult OnPostAssignLecturer(string lecturer, string id)
        {
            using (var context = new OnlineQuizContext())
            {
                Class c = context.Classes.Include(x => x.Course)
                    .Include(x => x.LecturerAccountNavigation).SingleOrDefault(x => x.ClassId == Int32.Parse(id));
                c.LecturerAccount = lecturer;
                context.Entry<Class>(c).State =
                    Microsoft.EntityFrameworkCore.EntityState.Modified;
                context.SaveChanges();
                TempData["SuccessMessage"] = "Assign Lecturer Successfully!";
            }
            return RedirectToPage("./Edit", new { id = id });
        }

        public IActionResult OnPostAssignCoworker(string lecturer, string id)
        {
            using (var context = new OnlineQuizContext())
            {
                Class c = context.Classes.Include(x => x.Course)
                    .Include(x => x.CoWorkerNavigation).SingleOrDefault(x => x.ClassId == Int32.Parse(id));
                c.CoWorker = lecturer;
                context.Entry<Class>(c).State =
                    Microsoft.EntityFrameworkCore.EntityState.Modified;
                context.SaveChanges();
                TempData["SuccessMessage"] = "Assign Co-Worker Successfully!";
            }
            return RedirectToPage("./Edit", new { id = id });
        }

        public IActionResult OnPostAssignStudent(string[] student, string id)
        {
            using (var context = new OnlineQuizContext())
            {
                foreach (var item in student)
                {
                    var t = new TakeClass
                    {
                        ClassId = Int32.Parse(id),
                        StudentAccount = item
                    };
                    context.Add(t);
                }
                context.SaveChanges();
                TempData["SuccessMessage"] = "Assign Students Successfully!";
            }

            return RedirectToPage("./Edit", new { id = id });
        }

        public IActionResult OnPostDelete(int id)
        {
            var c = _context.TakeClasses.Find(id);
            _context.TakeClasses.Remove(c);
            _context.SaveChanges();
            return RedirectToPage("./Edit", new { id = c.ClassId });
        }

        static bool IsAlphaNumericWithHyphen(string text)
        {
            Regex regex = new Regex("^[A-Z][A-Za-z0-9-]*$");

            return regex.IsMatch(text);
        }

        private ActionResult startUp(int? id)
        {
            var mySystem = new OnlineQuizContext();

            Class = _context.Classes.Include(x => x.Course)
                .Include(x => x.LecturerAccountNavigation).Include(x => x.CoWorkerNavigation).SingleOrDefault(x => x.ClassId == id);
            if (Class != null)
            {
                Lecturers = _context.Lecturers
                .Include(x => x.AccountNavigation).Where(c => c.Account != Class.LecturerAccount && c.Account != Class.CoWorker).ToList();
                Courses = _context.Courses.ToList();
                Students = _context.Students
                    .Include(x => x.AccountNavigation).Where(x=>x.AccountNavigation.RoleId == 4).ToList();
                TakeClass = mySystem.TakeClasses.Include(x => x.StudentAccountNavigation).Where(x => x.ClassId == id).ToList();

                List<Class> listClass = mySystem.Classes.Include(x => x.Course).Where(x => x.EndDate >= DateTime.Today).ToList();
                List<Student> s = new List<Student>();
                foreach (var item in Students)
                {
                    using (var context = new OnlineQuizContext())
                    {
                        int count = 0;
                        TakeClass t1 = new TakeClass();
                        foreach (var c in listClass)
                        {
                            t1 = mySystem.TakeClasses.Include(x => x.StudentAccountNavigation).SingleOrDefault(x => x.StudentAccount == item.Account && x.ClassId == c.ClassId && x.Class.CourseId == Class.CourseId);
                            if (t1 != null)
                            {
                                count++;
                            }
                        }
                        //TakeClass t = mySystem.TakeClasses.Include(x => x.StudentAccountNavigation).SingleOrDefault(x => x.StudentAccount == item.Account && x.ClassId == Class.ClassId);
                        if (count == 0)
                        {
                            s.Add(item);
                        }
                    }
                }
                StudentsNotAttend = s;
                return Page();
            }
            else
            {
                return RedirectToPage("/Courses/ManageCourses");
            }
            
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/StudentList.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizSystem.Models;

namespace QuizSystem.Pages.ClassManagement
{
    public class StudentListModel : PageModel
    {
        [BindProperty]
        public string Account { get; set; }

        [BindProperty]
        public Class Class { get; set; }

        [BindProperty]
        public Course Course { get; set; }

        OnlineQuizContext onlineQuizContext = new OnlineQuizContext();
        [BindProperty]
        public List<Student> students { get; set; }
      
        public void OnGet(int classId)
        {
            Class = onlineQuizContext.Classes.SingleOrDefault(x => x.ClassId == classId);
            Course = onlineQuizContext.Courses.SingleOrDefault(x => x.CourseId == Class.CourseId);
            students = new List<Student>();
            List<String> AccountList = new List<String>();
            List<TakeClass> takeClasses = onlineQuizContext.TakeClasses.Where(x => x.ClassId == classId).ToList();
            foreach (TakeClass takeClass in takeClasses)
            {
                AccountList.Add(takeClass.StudentAccount);
            }
            foreach(String account in AccountList) {
                students.Add(onlineQuizContext.Students.SingleOrDefault(x => x.Account == account));
            }
          
        }
    


    }
}

SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/TakeClass.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizSystem.Models;

namespace QuizSystem.Pages.ClassManagement
{
    public class TakeClassModel : PageModel
    {
        [BindProperty]
        public string StudentAccount {  get; set; }

        [BindProperty]
        public string ClassId { get; set; }

        OnlineQuizContext onlineQuizContext = new OnlineQuizContext();

        public void OnGet()
        {
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using QuizSystem.Models;

namespace QuizSystem.Pages.ClassManagement
{
    public class indexModel : PageModel
    {
        private readonly QuizSystem.Models.OnlineQuizContext _context;

        public indexModel(QuizSystem.Models.OnlineQuizContext context)
        {
            _context = context;
        }

        public IList<Class> Class { get; set; } = default!;
        public IList<Lecturer> Lecturers { get; set; } = default!;
        public int CourseID { get; set; }
        public string CourseCode { get; set; }

        public ActionResult OnGet(int? id)
        {
            return startUp(id);

        }
        public IActionResult OnPostCreate(string name, string course, string startdate, string enddate)
        {
            var mySystem = new OnlineQuizContext();
            var _c = mySystem.Classes.SingleOrDefault(x=>x.ClassName == name);
            if (String.IsNullOrEmpty(name))
            {
                TempData["FailMessage"] = "Class name is only contains alphabet, numbers and hyphen(ABC-123).";
            }
            else if (!IsAlphaNumericWithHyphen(name))
            {
                TempData["FailMessage"] = "Class name is only contains alphabet, numbers and hyphen(ABC-123).";
            }else if (DateTime.Parse(startdate) < DateTime.Today || DateTime.Parse(enddate) < DateTime.Today)
            {
                TempData["FailMessage"] = "Start date and End date must be in the future.";
            }
            else if (DateTime.Parse(startdate) > DateTime.Parse(enddate))
            {
                TempData["FailMessage"] = "Start date cannot be earlier than end date.";
            }
            else if (_c != null)
            {
                TempData["FailMessage"] = "Class already exist!";
            }
            else if(_c == null)
            {
                var c = new Class
                {
                    ClassName = name,
                    CourseId = Int32.Parse(course),
                    StartDate = DateTime.Parse(startdate),
                    EndDate = DateTime.Parse(enddate)
                };
                _context.Classes.Add(c);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Insert Successfully! Please assign Lecturer and Student for the class.";
                return RedirectToPage("./Edit", new { id = c.ClassId });
            }
            return RedirectToPage("index", new { id = course });
        }

        public IActionResult OnPostDelete(int id, int courseid)
        {
            var c = _context.Classes.Find(id);
            _context.Classes.Remove(c);
            _context.SaveChanges();
            return RedirectToPage("index", new { id = courseid });
        }

        public IActionResult OnGetFind(int id)
        {
            var c = _context.Classes.Find(id);
            return new JsonResult(c);
        }


        static bool IsAlphaNumericWithHyphen(string text)
        {
            Regex regex = new Regex("^[A-Z][A-Za-z0-9-]*$");

            return regex.IsMatch(text);
        }

        private ActionResult startUp(int? id)
        {
            var mySystem = new OnlineQuizContext();
            Course c = mySystem.Courses.FirstOrDefault(x => x.CourseId == id);
            if (c != null)
            {
                Class = mySystem.Classes.Include(x => x.Course)
                    .Include(x => x.LecturerAccountNavigation).Where(x => x.CourseId == id).ToList();
                Lecturers = mySystem.Lecturers
                    .Include(x => x.AccountNavigation).ToList();
                CourseID = (int)id;
                CourseCode = c.CourseCode;

                return Page();
            }
            else
            {
                return RedirectToPage("/Courses/ManageCourses");
            }

        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/CourseList.cshtml
@page
@model QuizSystem.Pages.ClassManagement.CourseListModel

@{
    ViewData["Title"] = "CourseList";
}

<h1>CourseList</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Course[0].CourseCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course[0].CourseName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Course) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                <a asp-page="./index" asp-route-id="@item.CourseId">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>

SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/TakeClass.cshtml
@page
@model QuizSystem.Pages.ClassManagement.TakeClassModel
@{
}

SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/index.cshtml
@page
@using Microsoft.EntityFrameworkCore
@using QuizSystem.Models
@model QuizSystem.Pages.ClassManagement.indexModel

@{
	ViewData["Title"] = Model.CourseCode ?? "Class management";
	var mySystem = new OnlineQuizContext();
            List<Class> Class = mySystem.Classes.Include(x => x.Course)
		.Include(x => x.LecturerAccountNavigation).Where(x => x.CourseId == Model.CourseID).ToList();
            List<Lecturer> Lecturers = mySystem.Lecturers
                .Include(x => x.AccountNavigation).ToList();
}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Bootstrap CRUD Data Table for Database with Modal Form</title>
	<link rel="stylesheet" href="~/css/classes/index.css" type="text/css" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
</head>
<style>
.modal .modal-dialog {
	max-width: 400px;
}
.modal .modal-header, .modal .modal-body, .modal .modal-footer {
	padding: 20px 30px;
}
.modal .modal-content {
	border-radius: 3px;
	font-size: 14px;
}
.modal .modal-footer {
	background: #ecf0f1;
	border-radius: 0 0 3px 3px;
}
.modal .modal-title {
	display: inline-block;
}
.modal .form-control {
	border-radius: 2px;
	box-shadow: none;
	border-color: #dddddd;
}
.modal textarea.form-control {
	resize: vertical;
}
.modal .btn {
	border-radius: 2px;
	min-width: 100px;
}	
.modal form label {
	font-weight: normal;
}	
.btn-popup{
  background: #2A4365;
    border-radius: 5px;
    color: white;
}

	.table > :not(:last-child) > :last-child > * {
		border: none; 
	}

.add-search-box{
	display: flex;
}

	#filterDate {
		display: inline-block;
		padding: 8px;
		margin-bottom: 5px;
		border: 1px solid #ccc;
		border-radius: 5px;
		font-size: 14px;
		color: black;
		background-color: white;
	}

		#filterDate option {
			font-size: 14px;
		}
</style>
<script type="text/javascript">
	$(document).ready(function () {
		// Activate tooltip
		$('[data-toggle="tooltip"]').tooltip();

		$('table .delete').on('click', function (){
			var id = $(this).parent().find('#id').val();
			$('#deleteEmployeeModal #id').val(id);
		});
	});

	function openFailModal(strMessage) {
		var myDiv = document.getElementById("MyModalFailAlertBory");
		myDiv.innerHTML = strMessage;
		$('#myFailModal').modal('show');
	}

	$(document).ready(function () {
		var msg = "@TempData["FailMessage"]";
		if (msg) openFailModal(msg);
	});


	function openSuccessModal(strMessage) {
		var myDiv = document.getElementById("MyModalSuccessAlertBory");
		myDiv.innerHTML = strMessage;
		$('#mySuccessModal').modal('show');
	}

	$(document).ready(function () {
		var msg = "@TempData["SuccessMessage"]";
		if (msg) openSuccessModal(msg);
	});

	

</script>


<body>
    @*<a href="#addEmployeeModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Add New Employee</span></a>*@
    <div id="addEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form method="post" asp-page="index" asp-page-handler="Create">
				<div class="modal-header">						
					<h4 class="modal-title">Add Class</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
							<div class="form-group">
								<label>Class Name</label>
								<input name="name" type="text" class="form-control" required>
							</div>
							
								<input name="course" value="@Model.CourseID" type="hidden" class="form-control" required>
							
							<div class="form-group">
								<label>Start Date</label>
								<input name="startdate" type="date" class="form-control" required>
							</div>
							<div class="form-group">
								<label>End Date</label>
								<input name="enddate" type="date" class="form-control" required>
							</div>
						</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-popup" value="Add">
				</div>
			</form>
		</div>
	</div>
</div>

	<div class="container-xl">
		<div class="table-responsive">
			<div class="table-wrapper">
				<div class="table-title">
					<div class="row">
						<div class="col-sm-6">
							<h2>Manage <b>Class of @Model.CourseCode</b></h2>
						</div>
						<div class="col-sm-6">
							<div class="add-search-box"
							<div class="search-box">
								<input type="text" id="search"  placeholder="Search by Class Name...">
								<button id="search-button" class="btn btn-primary" onclick="search()">Search</button>
					         </div>
							 <div class="filter-box">
	<label for="filterDate">Filter by Date:</label>
	<select id="filterDate">
		<option value="all">All Classes</option>
		<option value="past">Past Classes</option>
		<option value="ongoing">Ongoing Classes</option>
		<option value="upcoming">Upcoming Classes</option>
	</select>
</div>

							<a href="#addEmployeeModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Add New Class</span></a>
				        
						</div>
					</div>
				</div>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>ClassName</th>
							<th>StartDate</th>
							<th>EndDate</th>
							<th>Course</th>
							<th>Lecturer</th>
							
						</tr>
					</thead>
					<tbody>
						@foreach (var item in Class)
						{
							<tr class="class-row">
							<tr>
								<td>
									@Html.DisplayFor(modelItem => item.ClassName)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.StartDate)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.EndDate)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Course.CourseCode)
								</td>
								<td>
									@if (item.LecturerAccount == null)
									{
											<p>Not assigned yet</p>
									}else{
										@Html.DisplayFor(modelItem => item.LecturerAccount)
									}
								</td>
								<td>
									<a asp-page="./Details" asp-route-id="@item.ClassId">
										<i class="material-icons description">&#xe873;</i>

									</a>
									<a asp-page="./Edit" asp-route-id="@item.ClassId"><i class="material-icons" title="Edit">&#xE254;</i></a>
									@if (item.StartDate <= DateTime.Today && DateTime.Today < item.EndDate)
									{
									}else{
									<a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
									}
									<input type="hidden" name="id" id="id" value="@item.ClassId" />
								</td>
							</tr>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<a class="btn btn-info " asp-page="/Courses/ManageCourses">Back</a>
			</div>
		</div>
	</div>


<div id="deleteEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
				<form method="post" asp-page="index" asp-page-handler="Delete">
					<div class="modal-header">						
					<h4 class="modal-title">Delete Class</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">					
					<p>Are you sure you want to delete these Records?</p>
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-danger" value="Delete">
						<input type="hidden" name="id" id="id" />
						<input type="hidden" name="courseid" value="@Model.CourseID" />

				</div>
			</form>
		</div>
	</div>
</div>


	<div id="myFailModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Notice</h4>
					</div>
					<div id="MyModalFailAlertBory" class="modal-body alert alert-danger align-items-center text-center">
						Failed!
					</div>
				<div class="modal-footer">
					@*<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>*@
				</div>
		</div>
	</div>
	</div>

	    <div id="mySuccessModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Notice</h4>
                </div>
				<div id="MyModalSuccessAlertBory" class="modal-body alert alert-success align-items-center text-center">
                    success
                </div>
                <div class="modal-footer">
                    @*<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>*@
                </div>
            </div>
        </div>
    </div>
	<script src="~/js/searchClassByName.js"></script>
	<script src="~/js/filterClassByDate.js"></script>

		
</body>
</html>