SWP391-Quiz-System/QuizSystem/Models/Exam.cs
using System;
using System.Collections.Generic;

namespace QuizSystem.Models;

public partial class Exam
{
    public int ExamId { get; set; }

    public int? ClassId { get; set; }

    public string? LecturerAccount { get; set; }

    public string Title { get; set; } = null!;

    public string Summary { get; set; } = null!;

    public decimal? Score { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? Timer { get; set; }

    public int? TakingTimes { get; set; }

    public bool? Permission { get; set; }

    public virtual Class? Class { get; set; }

    public virtual ICollection<QuestionExam> QuestionExams { get; set; } = new List<QuestionExam>();

    public virtual ICollection<TakeExam> TakeExams { get; set; } = new List<TakeExam>();
}

SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using QuizSystem.Models;

namespace QuizSystem.Pages.ClassManagement
{
    public class DetailsModel : PageModel
    {
        private readonly QuizSystem.Models.OnlineQuizContext _context;

        public DetailsModel(QuizSystem.Models.OnlineQuizContext context)
        {
            _context = context;
        }

      public Class Class { get; set; } = default!;
        public IList<TakeClass> TakeClass { get; set; } = default!;

        public ActionResult OnGet(int? id)
        {
            return startUp(id);

        }
        private ActionResult startUp(int? id)
        {
            Class = _context.Classes.Include(x => x.Course)
                .Include(x => x.LecturerAccountNavigation).Include(x => x.CoWorkerNavigation).SingleOrDefault(x => x.ClassId == id);
            if (Class != null)
            {
                TakeClass = _context.TakeClasses.Include(x => x.StudentAccountNavigation).Where(x => x.ClassId == id).ToList();

                return Page();
            }
            else
            {
                return RedirectToPage("/Courses/ManageCourses");
            }

        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/Exams/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using QuizSystem.Models;

namespace QuizSystem.Pages.Exams
{
    public class DetailsModel : PageModel
    {
        OnlineQuizContext OnlineQuizContext = new OnlineQuizContext();
        [BindProperty]
        public Class Class { get;set; }
        //[BindProperty]
        //public Course course { get; set; }
        [BindProperty]
        public Exam exam { get;set; }
        [BindProperty]
        public String account { get; set; }
        public String message = "";
        public int numOfTaken = 0;
        public List<QuestionExam> questionList { get;set; }
        public List<List<QuestionExamAnswer>> answerList { get; set; }

        private bool checkLoginLecturer()
        {
            account = HttpContext.Session.GetString("account");
            string role = HttpContext.Session.GetString("role");
            //TH chua login
            if (account == null)
            {
                return false;
            }
            else
            {
                //TH login nhung ko phai tk lecturer
                if (role == null || role != "3")
                {
                    return false;
                }
            }
            return true;
        }
        private ActionResult startUp(int examID, string msg)
        {
            if (!checkLoginLecturer())
            {
                //redirect sang trang login
                return RedirectToPage("/Login/Login");
            }


            if (msg == "notAllowed") { message = "You are not allowed to edit/delete this exam!!"; }
            account = HttpContext.Session.GetString("account");
            numOfTaken = (OnlineQuizContext.TakeExams.Where(t => t.ExamId == examID).ToList()).Count;
            exam = OnlineQuizContext.Exams.Include(e=>e.Class).SingleOrDefault(e => e.ExamId == examID);
            if(exam != null && (exam.Class.LecturerAccount == account || exam.Class.CoWorker == account))
            {
                Class = OnlineQuizContext.Classes.Include(x => x.Course).SingleOrDefault(c => c.ClassId == exam.ClassId);
                //course = OnlineQuizContext.Courses.SingleOrDefault(c => c.CourseId == Class.Course.CourseId);
                questionList = OnlineQuizContext.QuestionExams.Where(q => q.ExamId == examID).ToList();

                answerList = new List<List<QuestionExamAnswer>>();

                if(questionList != null && questionList.Count > 0)
                {
                    foreach (QuestionExam q in questionList)
                    {
                        answerList.Add(OnlineQuizContext.QuestionExamAnswers.Where(ans => ans.QuesId == q.QuesId).ToList());
                    }
                }

                return Page();
            }
            else
            {
                //redirect sang incharge
                return RedirectToPage("/Courses/Lecturer/InChargeCourses");
            }
        }
        public ActionResult OnGet(int examID, string? msg)
        {
            return startUp(examID, msg==null? "":msg); 
        }

        public ActionResult OnPostDelete(string examID_raw, string classID)
        {
            int examID = Convert.ToInt32(examID_raw);

            Exam e = OnlineQuizContext.Exams.Include(e => e.Class).SingleOrDefault(e => e.ExamId == examID);

            if (HttpContext.Session.GetString("account") != e.LecturerAccount)
            {
                return startUp(examID, "notAllowed");
            }
            else
            {
                if (e != null)
                {
                    int count  = OnlineQuizContext.TakeExams.Where(t=>t.ExamId == e.ExamId).Count();
                    if (count >0)
                    {
                        return startUp(examID, "notAllowed");
                    }
                    else
                    {
                        try
                        {
                            OnlineQuizContext.Exams.Remove(e);
                            OnlineQuizContext.SaveChanges();
                            ViewData["myRedirect"] = "window.location = '" + "/Exams/Exams?courseID=" + e.Class.CourseId + "&&classID=" + Int32.Parse(classID) + "&&delMsg=success" + "'";
                            List<Exam> examsList = OnlineQuizContext.Exams.ToList();
                            if(examsList == null || examsList.Count == 0)
                            {
                                return startUp(examID, "");
                            }
                            else
                            {
                                return startUp(examsList[0].ExamId, "");
                            }
                        }
                        catch(Exception exception)
                        {
                            ViewData["myRedirect"] = "window.location = '" + "/Exams/Exams?courseID=" + e.Class.CourseId + "&&classID=" + Int32.Parse(classID) + "&&delMsg=error" + "'";
                            return startUp(examID, "");
                        }
                    }
                }
                else
                {
                    return RedirectToPage("/Courses/Lecturer/InChargeCourses");
                }
            }
        }

        public void OnPostEdit(string examID, string title, string summary, 
            DateTime startDate, DateTime endDate, int dur, int numOfAttempts)
        {
            try
            {
                int id = Int32.Parse(examID);
                Exam e = OnlineQuizContext.Exams.SingleOrDefault(e => e.ExamId == id);

                if (HttpContext.Session.GetString("account") != e.LecturerAccount)
                {
                    startUp(Int32.Parse(examID), "notAllowed");
                }
                else
                {
                    if (e != null)
                    {
                        e.Title = title == null ? title : title.Trim();
                        e.Summary = summary == null ? summary : summary.Trim();
                        e.StartDate = startDate;
                        e.EndDate = endDate;
                        e.Timer = dur;
                        e.TakingTimes = numOfAttempts;

                        OnlineQuizContext.Entry<Exam>(e).State =
                            Microsoft.EntityFrameworkCore.EntityState.Modified;
                        OnlineQuizContext.SaveChanges();
                    }
                    TempData["editSuccess"] = "Edit exam information successful!";
                    startUp(Int32.Parse(examID), "");
                }
            }
            catch(Exception e)
            {
                TempData["editError"] = "Edit exam information failed!";
                startUp(Int32.Parse(examID), "");
            }
        }

        public void OnPostAllow(string examID)
        {
            int id = Int32.Parse(examID);
            Exam e = OnlineQuizContext.Exams.SingleOrDefault(e => e.ExamId == id);

            if(e.Permission == true)
            {
                e.Permission = false;
            }
            else { e.Permission = true; }

            OnlineQuizContext.Entry<Exam>(e).State =
                        Microsoft.EntityFrameworkCore.EntityState.Modified;
            OnlineQuizContext.SaveChanges();

            startUp(Int32.Parse(examID), "");
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/Exams/Exams.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using QuizSystem.Models;

namespace QuizSystem.Pages.Exams
{
    public class ExamsModel : PageModel
    {
        OnlineQuizContext onlineQuizContext = new OnlineQuizContext();
        [BindProperty]
        public Course course { get; set; }
        [BindProperty]
        public List<Exam> Exams { get; set; }
        [BindProperty]
        public List<Class> Classes { get; set; }
        [BindProperty]
        public Class Class { get; set; }
        [BindProperty]
        public String account { get; set; }
        [BindProperty]
        public int numOfStu { get; set; }

        private ActionResult startUp(int courseID, int classID)
        {
            numOfStu = 0;
            account = HttpContext.Session.GetString("account");
            string role = HttpContext.Session.GetString("role");
            //TH chua login
            if (account == null)
            {
                return RedirectToPage("/Login/Login");
            }
            else
            {
                //TH login nhung ko phai tk lecturer
                if (role == null || role != "3")
                {
                    return RedirectToPage("/Login/Login");
                }
            }

            Classes = onlineQuizContext.Classes.
                Where(c => c.CourseId == courseID && (c.LecturerAccount == account || c.CoWorker == account))
                .ToList();

            //TH lecturer ko co class nao thuoc course nay hoac course ID truyen vao ko tim thay
            if (Classes == null || Classes.Count == 0)
            {
                return RedirectToPage("/Courses/Lecturer/InChargeCourses");
            }
            else
            {
                if (classID == 0)
                {
                    Class = Classes[0];
                }
                else
                {
                    Class = onlineQuizContext.Classes.SingleOrDefault(c => c.ClassId == classID && c.CourseId == courseID);
                }

                //TH ClassID truyen vao sai => chon class dau tien 
                if(Class == null)
                {
                    return RedirectToPage("/Exams/Exams", new {courseID = courseID, classID = Classes[0].ClassId });
                }

                course = onlineQuizContext.Courses.
                    SingleOrDefault(c => c.CourseId == courseID && (Class.LecturerAccount == account || Class.CoWorker == account));
                Exams = onlineQuizContext.Exams.Where(e => e.ClassId == Class.ClassId).ToList();

                numOfStu = (onlineQuizContext.TakeClasses.Where(tc => tc.ClassId == Class.ClassId).ToList()).Count;
                return Page();
            }
        }
        public ActionResult OnGet(int courseID, int? classID, string? delMsg)
        {
            if (delMsg != null)
            {
                if(delMsg == "error")
                {
                    TempData["delError"] = "Delete exam failed!";
                }

                if (delMsg == "success")
                {
                    TempData["delSuccess"] = "Delete exam successful!";
                }
            }

            if (classID == null || classID == 0)
            {
                return startUp(courseID, 0);
            }
            else
            {
                return startUp(courseID, (int)classID);
            }
        }

        public ActionResult OnPost(string lecturer,string courseID,string classID,
            string title, string summary, DateTime startDate, DateTime endDate, int dur, int numOfAttempts)
        {
            try
            {
                Exam e = new Exam();
                e.LecturerAccount = lecturer;
                e.Title = title == null ? title : title.Trim();
                e.Summary = summary == null? summary : summary.Trim();
                e.StartDate = startDate;
                e.EndDate = endDate;
                e.Timer = dur;
                e.TakingTimes = numOfAttempts;
                e.ClassId = Int32.Parse(classID);
                e.Score = 0;
                e.Permission = false;

                onlineQuizContext.Exams.Add(e);
                onlineQuizContext.SaveChanges();

                TempData["success"] = "Create exam successful!";
            }
            catch(Exception e)
            {
                Console.Out.WriteLine(e.Message);
                TempData["error"] = "Create exam failed!";
                //throw new Exception(e.Message);
                return startUp(Int32.Parse(courseID), Int32.Parse(classID));
            }

            return startUp(Int32.Parse(courseID), Int32.Parse(classID));
            //ViewData["myRedirect"] = "window.location = '" + "/Exams/Exams?courseID=" + Int32.Parse(courseID) + "&&" +"classID=" + Int32.Parse(classID) + "'";
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/Exams/StudentQuestionLog.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using QuizSystem.Models;

namespace QuizSystem.Pages.Exams
{
    public class StudentQuestionLogModel : PageModel
    {
        OnlineQuizContext OnlineQuizContext = new OnlineQuizContext();
        [BindProperty]
        public QuestionExam question { get; set; }
        [BindProperty]
        public TakeExam attempt { get; set; }
        [BindProperty]
        public List<QuestionExamAnswer> answers { get; set; }
        [BindProperty]
        public List<TakeAnswer> takeAnswers { get; set; }
        [BindProperty]
        public decimal score { get; set; }

        public ActionResult OnGet(int recordId, int quesId)
        {
            score = 0;
            question = OnlineQuizContext.QuestionExams.SingleOrDefault(q => q.QuesId == quesId);
            attempt = OnlineQuizContext.TakeExams.SingleOrDefault(t => t.TakeExamId == recordId);

            string account = HttpContext.Session.GetString("account");
            string role = HttpContext.Session.GetString("role");
            if(question == null)
            {
                return RedirectToPage("/Courses/Lecturer/InChargeCourses");
            }
            Exam exam = OnlineQuizContext.Exams.Include(e=>e.Class).SingleOrDefault(e => e.ExamId == question.ExamId);
            if (account == null || role != "3")
            {
                return RedirectToPage("/Login/Login");
            }

            if (exam == null || (exam.Class.LecturerAccount != account && exam.Class.CoWorker != account))
            {
                return RedirectToPage("/Courses/Lecturer/InChargeCourses");
            }
            
            if(question !=null && attempt != null)
            {
                answers = OnlineQuizContext.QuestionExamAnswers.Where(a => a.QuesId == question.QuesId).ToList();
                takeAnswers = OnlineQuizContext.TakeAnswers.Include(t=>t.Answer).Where(t => t.TakeExamId == attempt.TakeExamId && t.QuesId == question.QuesId).ToList();
                if(takeAnswers != null && takeAnswers.Count > 0)
                {
                    foreach(TakeAnswer a in takeAnswers)
                    {
                        if(question.Type == true)
                        {
                            if((bool)a.Answer.Correct)
                            {
                                score += (decimal)(a.Answer.Percent * question.Score) / 100;
                            }
                            else
                            {
                                score = 0;
                                break;
                            }
                        }
                        else
                        {
                            score = (bool)a.Answer.Correct? (decimal)question.Score : 0;
                        }
                    }
                }
                return Page();
            }
            else
            {
                return RedirectToPage("/Courses/Lecturer/InChargeCourses");
            }
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/Exams/Details.cshtml
@page
@using QuizSystem.Models
@model QuizSystem.Pages.Exams.DetailsModel
@{
    //Layout = null;
    ViewData["Title"] = "Exam Details";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/Content/font-awesome.min.css" type="text/css" />
    <link rel="stylesheet" href="~/css/exam.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Exams</title>
</head>
<body>
    @if (TempData["editSuccess"] != null)
    {
        <div class="alert alert-info alert-dismissible">
            @TempData["editSuccess"]
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        </div>
    }

    @if (TempData["editError"] != null)
    {
        <div class="alert alert-danger alert-dismissible">
            @TempData["editError"]
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        </div>
    }

    <div class="container">
        <div class="title text-center">
            <h1>EXAM</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/">Home</a></li>
                    <li class="breadcrumb-item"><a href="~/Courses/Lecturer/InChargeCourses">In-charge courses</a></li>
                    <li class="breadcrumb-item"><a href="~/Exams/Exams?courseID=@Model.Class.Course.CourseId">@Model.Class.Course.CourseCode</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@Model.exam.Title</li>
                </ol>
            </nav>
        </div>

        <hr />
        @if(Model.message != ""){
            <div class="alert alert-danger">
                @Model.message
            </div>
        }
        <div ></div>
        <div class="exam-info">
            <div class="exam-title">@Model.exam.Title</div>
            <div class="exam-summary">Summary: @Model.exam.Summary</div>
            <div class="exam-startdate">Start date: @Model.exam.StartDate</div>
            <div class="exam-enddate">End date: @Model.exam.EndDate</div>
            <div class="exam-timer">Time: @Model.exam.Timer</div>
            <div class="exam-attempts">Attempts: @Model.exam.TakingTimes</div>
        </div>
        

        <div class="exam-action">
            <div class="link-action">
                @if (Model.exam != null && (Model.account == Model.exam.LecturerAccount) && Model.numOfTaken == 0)
                {
                    <a class="edit-exam-info" id="edit-exam" onclick="showEditModal('@Model.exam.ExamId',
                                                                        '@Model.exam.Title','@Model.exam.Summary',
                                                                        '@Model.exam.StartDate','@Model.exam.EndDate',
                                                                        '@Model.exam.Timer','@Model.exam.TakingTimes')">
                        <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                        Edit info
                    </a>
                    <a class="edit-exam-question-list" href="~/Questions/Questions?examID=@Model.exam.ExamId">
                        <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                        Edit questions
                    </a>
                }
                @if(Model.exam != null){
                    <a class="exam-statistic" href="~/Exams/Statistics?examID=@Model.exam.ExamId">
                        <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                        View statistics
                    </a>
                }
                @* <a class="exam-preview">
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                    Preview
                </a> *@
            </div>
            <div id="exam-page-btn">
            <button id="delete-exam" onclick="showDeleteModal()">
                DELETE
            </button>


            <form method="post" asp-page="Details" asp-page-handler="Allow">
                <input type="hidden" name="examID" value="@Model.exam.ExamId">
                @if (Model.exam.Permission == true)
                {
                    <input id="permission-exam" type="submit" value="NOT ALLOW" style="background-color: red">
                }
                else
                {
                    <input id="permission-exam" type="submit" value="ALLOW">
                }
            </form>
            </div>
        </div>

        <hr />
        <h3>QUESTIONS</h3>
        <div class="exam-question-list">
            @if(Model.questionList == null || Model.questionList.Count == 0){
                <h2>There is no question in this exam!</h2>
            }else{
                @for (int i = 0; i < Model.questionList.Count; i++)
                {
                    <div class="question-container">
                        <div class="question">
                            Question: @Model.questionList[i].Content
                        </div>
                        <div class="answers">
                            @for (int j = 0; j < Model.answerList[i].Count; j++)
                            {
                                @if (@Model.answerList[i][j].Correct == true)
                                {
                                    <p class="answer answer-true">
                                        @Model.answerList[i][j].Content
                                    </p>
                                }
                                else
                                {
                                    <p class="answer answer-false">
                                        @Model.answerList[i][j].Content
                                    </p>
                                }
                            }
                        </div>
                    </div>
                }
            }
        </div>
    </div>

    <div id="modal-overlay" onclick="hideModal()"></div>
    <div id="delete-exam-modal">
        <div class="confirm-message">
            Do you want to delete this exam?
        </div>
        <div class="modal-action">
            <div class="modal-elm">
                <button id="delete-cancel" onclick="hideModal()">Cancel</button>
            </div>
            <div class="modal-elm">
                <form class="delete-form" method="post" asp-page="Details" asp-page-handler="Delete">
                    <input type="hidden" name="examID_raw" value="@Model.exam.ExamId" />
                    <input type="hidden" name="classID" value="@Model.Class.ClassId" />
                    
                    <input id="delete-confirm" type="submit" value="Delete" />
                </form>
            </div>
        </div>
    </div>

    <div id="edit-exam-modal">
        <div class="header-modal">
            Edit exam's information
        </div>
        <div class="body-modal">
            <form name="editExamForm" method="post" asp-page="Details" asp-page-handler="Edit">
                <input name="examID" type="hidden" value="@Model.exam.ExamId">
                <div class="form-group">
                    <label>Title</label>
                    <input name="title" type="text" class="form-control" required>
                </div>
                <p id="alert-title" style="color: red; font-weight: bold;"></p>
                <div class="form-group">
                    <label>Summary</label>
                    <input name="summary" type="text" class="form-control" required>
                </div>
                <p id="alert-sum" style="color: red; font-weight: bold;"></p>
                <div class="exam-dl">
                    <label>Start</label>
                    <input name="startDate" type="datetime-local" id="start-date" required />
                    <label>End</label>
                    <input name="endDate" type="datetime-local" id="end-date" required/>

                    <p id="alert-date" style="color: red; font-weight: bold;"></p>
                </div>
                <div class="form-group">
                    <label>Duration (Sec)</label><div id="time-display" style="display:inline;"></div>
                    <input name="dur" type="number" class="form-control" required>
                        <p id="alert-dur" style="color: red; font-weight: bold;"></p>
                </div>
                <div class="form-group">
                    <label>Number of attempts</label>
                    <input name="numOfAttempts" type="number" class="form-control" required min="1" max="999">
                        <p id="alert-atp" style="color: red; font-weight: bold;"></p>
                </div>

                <div class="modal-btn">
                    <div class="btn-cancel moda-btn" onclick="hideModal()" style="cursor: pointer; text-align: center;">
                        Cancel
                    </div>
                    <input id="submit-btn" type="submit" class="moda-btn btn-blue" value="Save">
                </div>
            </form>
        </div>
    </div>

    <script src="~/js/exam.js"></script>
    @if (ViewData["myRedirect"] != null)
    {
        <script>
            @Html.Raw(ViewData["myRedirect"])
        </script>
    }
</body>
</html>