SWP391-Quiz-System/QuizSystem/Controllers/LoginController.cs
using System.Data;
using System.Security.Claims;
using System.Web;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
//using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Mvc;
using QuizSystem.Models;
using QuizSystem.Services.Encryption;
using QuizSystem.Services.ValidationService;

namespace QuizSystem.Controllers {
    public class LoginController : Controller {
        OnlineQuizContext onlineQuizContext;
        public LoginController(OnlineQuizContext _context) {
            onlineQuizContext = _context;
        }
        public IActionResult Index() {
            return RedirectToPage("/Login/Login");
        }

        public async Task LoginWithGoogle() {
            await HttpContext.ChallengeAsync(GoogleDefaults.AuthenticationScheme, new AuthenticationProperties() {
                RedirectUri = Url.Action("GoogleResponse")
            });

        }

        public async Task<IActionResult> GoogleResponse() {
            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            var claims = result.Principal.Identities.FirstOrDefault().Claims.Select(claim => new {
                claim.Issuer,
                claim.OriginalIssuer,
                claim.Type,
                claim.Value
            });
            string a = "";

            foreach (var c in claims)
            {
                if (c.Type.Substring(c.Type.LastIndexOf("/") + 1) == "emailaddress")
                {
                    a = c.Value;
                }
            }

            //return Json(a); //=> dong nay dung de test xem da lay dc email ra chua

            User? user = onlineQuizContext.Users.FirstOrDefault(user => user.Email == a);
            //if (user == null && (new ValidationService().ValidateEmail(a, out var error))) {
            //    await Logout();
            //    return Redirect("~/Login/Create_Account?u=" + HttpUtility.UrlEncode(a.Encrypt()));
            //}

            //check if mail has @fpt.edu.vn
            if (
                //(a.Substring(a.IndexOf("@"), a.Length - a.IndexOf("@")) != "@fpt.edu.vn"
                //&& a.Substring(a.IndexOf("@"), a.Length - a.IndexOf("@")) != "@fe.edu.vn")
                //||
                user == null) {
                await HttpContext.SignOutAsync();
                return Redirect("~/Login/Login");
            }
            //create session
            HttpContext.Session.SetString("user", user.Email);
            HttpContext.Session.SetString("account", user.Account);
            HttpContext.Session.SetString("role", user.RoleId.ToString());

            switch (user.RoleId) {
                case 1:
                    return Redirect("~/Index");
                    break;
                case 2:
                    return Redirect("~/Index");
                    break;
                case 3:
                    return Redirect("~/Index");
                    break;
                case 4:
                    return Redirect("~/Dashboard/StudentDashboard");
                    break;
            }
            return Redirect("~/Login/Login");
        }

        public async Task<IActionResult> Logout() {
            await HttpContext.SignOutAsync();
            HttpContext.Session.Remove("user");
            HttpContext.Session.Remove("role");
            return Redirect("~/Login/Login");
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/ClassManagement/Profile.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizSystem.Models;
using QuizSystem.Repositories;
using Microsoft.Extensions.Primitives;

namespace QuizSystem.Pages.ClassManagement {
    [Authorize(Policy = "Student and Lecturer")]
    public class ProfileModel : PageModel {
        public User? UserData { get; set; }
        public List<Class> ClassList { get; set; }
        public bool IsStudent { get; set; }
        UserRepository userRepository;
        StudentRepository studentRepository;
        LecturerRepository lecturerRepository;

        public ProfileModel(OnlineQuizContext _context) {
            userRepository = new UserRepository(_context);
            studentRepository = new StudentRepository(_context);
            lecturerRepository = new LecturerRepository(_context);
        }

        public async Task<IActionResult> OnGetAsync(string? u, string? id) {
            TempData["Message"] = "Cannot retrieve user data.";
            TempData["Color"] = "danger";
            var lastPage = "Index";
            var referer = Request.Headers["Referer"];
            if (!StringValues.IsNullOrEmpty(referer)) lastPage = referer.Last() ?? "Index";




            string? a = HttpContext.Session.GetString("account");

            User? getter = null;
            if (a != null) {
                getter = await userRepository.Find(a);
            }
            User? profiler = await userRepository.Find(u);
            if (getter == null || profiler == null) return Redirect(lastPage);

            if (getter.RoleId == 3) {
                if (profiler.RoleId != 4) return Redirect(lastPage);
                
                var classList = await lecturerRepository.GetClassListAsync(getter.Account);
                profiler.Student = await studentRepository.Find(profiler.Account);

                if (profiler.Student == null) return Redirect(lastPage);
                if (!getCommonClasses(classList, await studentRepository.GetClassListAsync(profiler.Account)).Any()) return Redirect(lastPage);

                IsStudent = true;
                ClassList = classList;
            }
            else {
                if (profiler.RoleId != 3) return Redirect(lastPage);

                var classList = await studentRepository.GetClassListAsync(getter.Account);
                profiler.Lecturer = await lecturerRepository.Find(profiler.Account);

                if (profiler.Lecturer == null) return Redirect(lastPage);
                if (!getCommonClasses(classList, await lecturerRepository.GetClassListAsync(profiler.Account)).Any()) return Redirect(lastPage);

                IsStudent = false;
                ClassList = classList;
            }
            UserData = profiler;

            TempData["Message"] = null;
            TempData["Color"] = null;
            return Page();

            List<Class> getCommonClasses(List<Class> list1, List<Class> list2) {
                List<Class> ret = new List<Class>();

                foreach (var c in list1) {
                    if (list2.Contains(c)) ret.Add(c);
                }

                return ret;
            }
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/Login/ChangePassword.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using QuizSystem.Models;

namespace QuizSystem.Pages.Login
{
    public class ChangePasswordModel : PageModel
    {
        public string Alert { get; set; }
        public string Notice { get; set; }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("user") == null)
            {
                return RedirectToPage("/Login/Login");
            }
            return Page();
        }
        public void OnPost(string oldpass, string newpass, string confirmpass)
        {
            User u = null;
            Alert = null;
            Notice = null;
            try
            {
                var mySystem = new OnlineQuizContext();
                string email = HttpContext.Session.GetString("user");
                u = mySystem.Users.SingleOrDefault(u => u.Email == email);
                if (!BCrypt.Net.BCrypt.Verify(oldpass, u.Password))
                {
                    Alert = "Password incorrect! Please try again.";
                    Notice = null;
                }
                else if (newpass == oldpass)
                {
                    Alert = "Current Password and Confirm Password are the same! Please try again.";
                    Notice = null;
                }
                else if (newpass != confirmpass && newpass != oldpass)
                {
                    Alert = "New Password and Confirm Password not match! Please try again.";
                    Notice = null;
                }
                else if (newpass == confirmpass && newpass != oldpass)
                {
                    u.Password = newpass;
                    mySystem.Entry<User>(u).State = EntityState.Modified;
                    mySystem.SaveChanges();
                    Notice = "Change sucessfully!";
                    Alert = null;
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/Login/Create_Account.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizSystem.Models;
using QuizSystem.Repositories;
using QuizSystem.Services.Encryption;
using QuizSystem.Services.ExtensionMethods;
using QuizSystem.Services.MailingService;
using QuizSystem.Services.ValidationService;
using System.Text;
using System.Web;

namespace QuizSystem.Pages.Login {
    public class Create_AccountModel : PageModel {
        private UserRepository _userRepository;
        private ISendMailService _mailService;
        private StudentRepository _studentRepository;

        public string? Email { get; set; } = null;

        public Create_AccountModel(ISendMailService mailService, OnlineQuizContext context) {
            _studentRepository = new StudentRepository(context);
            _userRepository = new UserRepository(context);
            _mailService = mailService;
        }

        public async void OnGet(string? u) {
            string? acc = u.Decrypt();
            if (acc != null && (new ValidationService().ValidateEmail(acc, out var error))) {
                Email = acc;
            }
        }

        public async Task<IActionResult> OnPost(ValidationService validation) {
            await Console.Out.WriteLineAsync("Email = " + validation.Email + "\nAccount" + validation.Account);
            var result = await validation.ValidateAll(false);
            if (result.IsPassed()) {
                try {
                    User u = new User() {
                        Account = validation.Account,
                        Email = validation.Email,
                        Password = BCrypt.Net.BCrypt.HashPassword(validation.Password),
                        RoleId = 4
                    };

                    Student s = new Student() {
                        Account = validation.Account,
                        Mssv = validation.Account,
                        Dob = validation.DoB,
                        Major = validation.Major,
                        Phone = validation.Phone,
                        StudentName = validation.Name
                    };

                    await _userRepository.Add(u);
                    await _studentRepository.Add(s);
                    await _mailService.SendMailWithTemplateAsync(u, MailObjective.CreateAccount);
                }
                catch (Exception ex) {
                    await Console.Out.WriteLineAsync(ex.Message);
                    TempData["Message"] = "Cannot create user";
                    TempData["Color"] = "danger";
                    return Page();
                }

                TempData["Message"] = "Create account successfully! Please log in to your new account.";
                TempData["Color"] = "success";
                return RedirectToPage("/Login/Login");
            }
            else {
                TempData["Color"] = "danger";
                if (result.Errors.Count > 1) {
                    TempData["Message"] = "Cannot create user:";
                    foreach (var s in result.Errors) {
                        TempData["Message"] += "<br/>  -  " + s;
                    }
                }
                else TempData["Message"] = result.Errors[0];
                return Page();
            }
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/Login/Forgot_Password.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizSystem.Models;
using QuizSystem.Repositories;
using QuizSystem.Services.Encryption;
using QuizSystem.Services.MailingService;

namespace QuizSystem.Pages.Login {
    public class Forgot_PasswordModel : PageModel {
        private UserRepository userRepository;
        private ISendMailService mailService;


        public Forgot_PasswordModel(ISendMailService _mailService, OnlineQuizContext _context) {
            mailService = _mailService;
            userRepository = new UserRepository(_context);
        }

        public void OnGet() {
            if (TempData["Message"] == null) {
                TempData["Message"] = "Enter your recovery e-mail to create new password.";
                TempData["Color"] = "info";
            }
        }

        public async Task<IActionResult> OnPost(string email) {
            if (await userRepository.IsEmailAvailable(email)) {
                TempData["Message"] = $"Cannot find user's email \"{email}\". Please check your entered e-mail address and try again.";
                TempData["Color"] = "warning";
                return Page();
            }
            else {
                User user = await userRepository.FindUserByEmail(email);
                string password = await userRepository.ResetPassword(user.Account);
                user.Password = password;
                bool isMailSent = await mailService.SendMailWithTemplateAsync(user, MailObjective.ForgotPassword);

                //bool isMailSent = await mailService.SendMailAsync("longdhhe160008@fpt.edu.vn", "Hi", "Hello");
                if (!isMailSent) {
                    TempData["Message"] = "Cannot send recovery e-mail. Please check your entered e-mail address and try again.";
                    TempData["Color"] = "danger";
                    return Page();
                }
                else {
                    TempData["Message"] = "Send email successfully! Please check your email to get your new password.";
                    TempData["Color"] = "success";

                    return RedirectToPage("Reset_Password", new { u = email.Encrypt() });
                }

            }
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/Login/ChangePassword.cshtml
@page
@model QuizSystem.Pages.Login.ChangePasswordModel
@{
    //Layout = null;
    ViewData["Title"] = "Change Password";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/Login.css" type="text/css" />
    <link rel="stylesheet" href="~/css/StyleAlert.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>Change Password</title>
</head>
<body>

    <div class="app-container">
        <div class="app-name"></div>
        <div class="form">
            <form class="login-form" method="post">
                <div class="label-input">
                    <i></i>
                    Current Password
                </div>
                <input id="pw" name="oldpass" type="password" placeholder="Current Password" required />

                <div class="label-input">
                    <i></i>
                    New Password
                </div>
                <input id="pw" name="newpass" type="password" placeholder="New Password" required />

                <div class="label-input">
                    <i></i>
                    Confirm Password
                </div>
                <input id="pw" name="confirmpass" type="password" placeholder="Confirm Password" required />
                <div class="group-btn d-flex">
                    <input type="submit" id="submit" class="form-submit" value="Submit" />
                </div>
                <div>
                    @if (@Model.Alert != null)
                    {
                        <label style="display:block">
                            <input type="checkbox" class="alertCheckbox" autocomplete="off" />
                            <div class="alert error">

                                <span class="alertText">
                                    @Model.Alert
                                    <br class="clear" />
                                </span>
                            </div>
                        </label>
                    }

                    @if (@Model.Notice != null)
                    {
                        <label style="display:block">
                            <input type="checkbox" class="alertCheckbox" autocomplete="off" />
                            <div class="alert success">
                                <span class="alertText">
                                    @Model.Notice
                                    <br class="clear" />
                                </span>
                            </div>
                        </label>
                    }
                </div>
            </form>
        </div>
    </div>
</body>
</html>

SWP391-Quiz-System/QuizSystem/Pages/Login/Forgot_Password.cshtml
@page "{Forgot_Password?}/{action?}"
@model QuizSystem.Pages.Login.Forgot_PasswordModel
@{
    Layout = null;
    ViewData["Title"] = "Forgot Password";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/Login.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>Login</title>
    <script>
        function disableSubmitButton() {
            document.getElementById("submit").value = "Sending Email. . . "
            document.getElementById("submit").disabled = true;
            document.getElementById("submit").style.background = "rgb(96 106 135)";
        }
    </script>
</head>
<body>
    <div class="app-container">
        @Html.Partial("_NoticeMessagePartial")
        <div class="form-container">
            <div class="app-name">FPTQuiz</div>
            <div class="form">
                @using (Html.BeginForm("Forgot_Password", "Login", FormMethod.Post, new { @class = "login-form", @onsubmit = "disableSubmitButton();" })) {
                    <div class="form-group">
                        <div class="label-input">
                            <i></i>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-envelope" viewBox="0 0 22 22">
                                <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
                            </svg> Email address
                        </div>
                        @Html.TextBox("email", null, new { required = true, placeholder = "E-mail"})
                    </div>
                    <div class="btn-group d-flex">
                        <input type="submit" id="submit" class="form-submit" value="Send Email" />
                    </div>
                }
            </div>
        </div>
    </div>
</body>

SWP391-Quiz-System/QuizSystem/Pages/Login/Login.cshtml
@page
@model QuizSystem.Pages.Login.LoginModel
@{
    Layout = null;
    ViewData["Title"] = "Login";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/Login.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>Login</title>
</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        switch (HttpContext.Session.GetString("role"))
        {
            case "1":
                Response.Redirect("/Index");
                break;
            case "2":
            Response.Redirect("/Index");
                break;
            case "3":
            Response.Redirect("/Index");
                break;
            case "4":
            Response.Redirect("/Dashboard/StudentDashboard");
                break;
        }
    }

    <div class="app-container">
        @Html.Partial("_NoticeMessagePartial")
        <div class="app-name">FPTQuiz</div>
        <div class="form">
            <form class="login-form" method="post" asp-page="Login">
                <div class="label-input">
                    <i></i>
                    Email address
                </div>
                <input id="email" type="text" placeholder="Email" asp-for="@Model.Email" required/>

                <div class="label-input">
                    <i></i>
                    Password
                </div>
                <input id="pw" type="password" placeholder="Password" asp-for="@Model.Password" required/>
                <p id="alert-pwd" style="color: red; font-weight: bold;"></p>

                <div class="group-btn d-flex">
                    <a class="forgot-pass" asp-page="/Login/Forgot_Password">Forgot password?</a>
                    <input type="submit" id="submit" class="form-submit" value="Sign in" />
                </div>
            </form>

            <div class="login-fail-msg">@Model.Msg</div>

            <a class="gg-login" asp-controller="Login" asp-action="LoginWithGoogle">
                <img src="~/Images/google.jpg" width="24" height="24" />
                Login with @@FPT.EDU.VN
            </a>
        </div>
    </div>
</body>
</html>

SWP391-Quiz-System/QuizSystem/Pages/Login/Reset_Password.cshtml
@page
@model QuizSystem.Pages.Login.Reset_PasswordModel
@{
    Layout = null;
    ViewData["Title"] = "Reset Password";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/Login.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>Login</title>
    <script>
        function disableSubmitButton() {
            document.getElementById("submit").value = "Creating Account. . . "
            document.getElementById("submit").disabled = true;
            document.getElementById("submit").style.background = "rgb(96 106 135)";
        }
    </script>
</head>
<body>
    <div class="app-container">
        @Html.Partial("_NoticeMessagePartial")
        <div class="form-container">
            <div class="app-name">FPT QUIZ</div>
            <div class="form">
                @using (Html.BeginForm("Reset_Password", "Login", FormMethod.Post, new { @class = "login-form", onsubmit = "return validateData('oldPassword','password', 'confirmPassword');" })) {
                    @Html.TextBoxFor(model => model.Email, new {hidden = true, @readonly = true})
                    if (Model.OldPassword != null) {
                        @Html.TextBoxFor(model => model.OldPassword, new {hidden = true, @readonly = true})
                    }
                    else {
                        <div class="form-group">
                            <div class="label-input">
                                <i></i>
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-unlock" viewBox="0 0 22 22">
                                    <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2zM3 8a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1H3z" />
                                </svg> @Html.Label("oldPassword", "Old Password")
                            </div>
                            @Html.Password("oldPassword", Model.OldPassword, new { placeholder = "Old Password", onkeyup = "markInvalidData('oldPassword');"})
                            <div id="oldPasswordReq" class="mb-3" style="font-size:small;color:red;">
                                <ul class="list-group-horizontal mb-0" style="list-style-type: disc;">
                                    <li class="me-2">
                                        You must enter your old password.
                                    </li>
                                </ul>
                            </div>
                        </div>
                    }
                    <div class="form-group">
                        <div class="label-input">
                            <i></i>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-key" viewBox="0 0 22 22">
                                <path d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8zm4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5z" />
                                <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                            </svg> @Html.Label("password", "Password")
                        </div>
                        @Html.Password("password", null, new { placeholder = "Password", onkeyup = "markInvalidData('password');"})
                        <div id="passwordReq" class="mb-3" style="font-size:small;">
                            <ul class="list-group-horizontal mb-0" style="list-style-type: disc;">
                                <li class="me-2">
                                    Password must be 8 to 32 characters long
                                </li>
                            </ul>
                            <ul class="list-group-horizontal" style="list-style-type: disc;">
                                <li class="me-2">
                                    Password must contains at least one character each of the following
                                    <ul class="list-group-horizontal" style="list-style-type: circle;">
                                        <li class="">
                                            Uppercase letter
                                        </li>
                                        <li class="">
                                            Lowercase letter
                                        </li>
                                    </ul>
                                    <ul class="list-group-horizontal" style="list-style-type: circle;">
                                        <li class="me-2">
                                            Special characters (@Html.Raw(".,<>@... "))
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label-input">
                            <i></i>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-lock" viewBox="0 0 22 22">
                                <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2zM5 8h6a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1z" />
                            </svg> @Html.Label("confirmPassword", "Confirm password")
                        </div>
                        @Html.Password("confirmPassword", null, new { placeholder = "Confirm password", onkeyup = "markInvalidData('confirmPassword');"})
                        <div id="confirmPasswordReq" class="mb-3" style="font-size:small;">
                            <ul class="list-group-horizontal" style="list-style-type: disc;">
                                <li class="me-2">
                                    Must match with password
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="btn-group d-flex">
                        <input type="submit" id="submit" class="form-submit" value="Update Password" />
                    </div>
                }
            </div>
        </div>
    </div>
    <script src="~/js/CreateAccountValidate.js"></script>
</body>