SWP391-Quiz-System/QuizSystem/Models/Lecturer.cs
using System;
using System.Collections.Generic;

namespace QuizSystem.Models;

public partial class Lecturer
{
    public string Account { get; set; } = null!;

    public string LecturerName { get; set; } = null!;

    public string? Phone { get; set; }

    public virtual User AccountNavigation { get; set; } = null!;

    public virtual ICollection<Class> ClassCoWorkerNavigations { get; set; } = new List<Class>();

    public virtual ICollection<Class> ClassLecturerAccountNavigations { get; set; } = new List<Class>();
}

SWP391-Quiz-System/QuizSystem/Pages/Courses/Lecturer/InChargeCourses.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizSystem.Models;

namespace QuizSystem.Pages.Courses.Lecturer
{
    public class InChargeCoursesModel : PageModel
    {
        OnlineQuizContext onlineQuizContext = new OnlineQuizContext();
        public List<Course> courseList { get; set; }
        public String account { get; set; }

        private void startUp()
        {
            account = HttpContext.Session.GetString("account");

            //lay ra tat ca class ma lecturer dong vai tro la lecturer hoac coworker
            List<Class> classList = onlineQuizContext.Classes.Where(c => c.LecturerAccount == account || c.CoWorker == account).ToList();
            List<int> courseIDListDup = new List<int>();
            List<int> courseIDList = new List<int>();
            courseList = new List<Course>();

            //TH tim thay class => ko co class nao thi courseList ko co phan tu nao
            if(classList != null && classList.Count > 0)
            {
                foreach (Class c in classList)
                {
                    courseIDListDup.Add((int)c.CourseId);
                }

                courseIDList = courseIDListDup.Distinct().ToList();

                foreach (int courseID in courseIDList)
                {
                    courseList.Add(onlineQuizContext.Courses.SingleOrDefault(c => c.CourseId == courseID));
                }
            }
        }
        public IActionResult OnGet()
        {
            if (!User.Identity.IsAuthenticated || HttpContext.Session.GetString("role") != "3")
            {
                return Redirect("~/Login/Login");
            }
            else
            {
                startUp();
                return Page();
            }
        }

        public IActionResult OnPostSearch(string code)
        {
            startUp();
            if (!(code==null || code.Length == 0) && courseList != null && courseList.Count > 0)
            {
                for (int i = 0; i < courseList.Count; i++)
                {
                    if (!courseList[i].CourseCode.ToLower().Contains(code.ToLower()))
                    {
                        courseList.Remove(courseList[i]);
                        i--;
                    }
                }
            }
            
            return Page();
        }
    }
}

SWP391-Quiz-System/QuizSystem/Pages/Courses/ManageCourses.cshtml.cs
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using QuizSystem.Models;

namespace QuizSystem.Pages.Courses
{
    public class ManageCoursesModel : PageModel
    {

        [BindProperty]
        public int CourseId { get; set; }

        [BindProperty]
        public string CourseCode { get; set; }

        [BindProperty]
        public string CourseName { get; set; }

        [BindProperty]
        public string Description { get; set; }


        OnlineQuizContext onlineQuizContext = new OnlineQuizContext();
        [BindProperty]
        public List<Course> courses { get; set; }

        [BindProperty]
        public Course Course { get; set; }


        public void OnGet()
        {
            courses = onlineQuizContext.Courses.ToList();
        }


        private bool IsValidated(string input)
        {
            return !string.IsNullOrEmpty(input) && Regex.IsMatch(input, @"^[A-Za-z0-9.-]+$");
        }

        public void OnPostCreate(String coursecode, String coursename, String coursedes)
        {
            // check existed course code
            Course c = onlineQuizContext.Courses.SingleOrDefault(c => c.CourseCode == coursecode);
            Course newcourse = new Course();
            if (!IsValidated(coursecode))
            {
                ViewData["ErrorMessage"] = "Course code must be only letters, numbers and (.), (-) characters";
            }
            else
            if (c == null)
            {

                newcourse.CourseCode = coursecode;
                newcourse.CourseName = coursename;
                newcourse.Description = coursedes;
                onlineQuizContext.Courses.Add(newcourse);
                onlineQuizContext.SaveChanges();
                ViewData["myRedirect"] = "window.location = '" + "/Courses/ManageCourses" + "'";

            }
            else
            {
                ViewData["ErrorMessage"] = "Course code already exists.";
            }

        }

        public void OnPostDelete(String coursecode)
        {
            //code delete
            Course c = onlineQuizContext.Courses.SingleOrDefault(c => c.CourseCode == coursecode);
            if (c != null)
            {
                onlineQuizContext.Courses.Remove(c);
                onlineQuizContext.SaveChanges();

            }
            ViewData["myRedirect"] = "window.location = '" + "/Courses/ManageCourses" + "'";
        }


        public void OnPostEdit(String initialCourseCode, String coursecode, String coursename, String coursedes)
        {
            
            Course c = onlineQuizContext.Courses.FirstOrDefault(c => c.CourseCode.Equals(initialCourseCode));
                if (c != null)
                {
                    c.CourseCode = coursecode;
                    c.CourseName = coursename;
                    c.Description = coursedes;
                    onlineQuizContext.SaveChanges();
                    
                    ViewData["myRedirect"] = "window.location = '" + "/Courses/ManageCourses" + "'";
                }
            
            
        }

    }
}

SWP391-Quiz-System/QuizSystem/Pages/Courses/Lecturer/InChargeCourses.cshtml
@page
@using QuizSystem.Models
@model QuizSystem.Pages.Courses.Lecturer.InChargeCoursesModel
@{
    ViewData["Title"] = "In charge courses";
    //Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/Content/font-awesome.min.css" type="text/css" />
    <link rel="stylesheet" href="~/css/in_charge_courses.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>Courses</title>
</head>
<body>
    <div class="main-container">
        <div class="title">
            <h1>Welcome, @Model.account</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">In-charge courses</li>
                </ol>
            </nav>
        </div>

        <h3>In charge: </h3>

        <div class="body-container d-flex">
            <div class="course-container d-flex">
                @if(Model.courseList != null && Model.courseList.Count > 0){
                    @foreach (Course c in Model.courseList)
                    {
                        <a class="course" href="~/Exams/Exams?courseID=@c.CourseId">
                            <div class="course-code">
                                @c.CourseCode
                            </div>
                            <div class="course-name">
                                @c.CourseName
                            </div>
                            <div class="course-des">
                                @c.Description
                            </div>
                        </a>
                    }
                }else{
                    <h2>No course found!</h2>
                }
                
            </div>
            <div class="search-and-sort">
                <div class="search">
                    <form method="post" asp-page="InChargeCourses" asp-page-handler="Search">
                        <input id="code" name="code" placeholder="Course code" type="text" />
                        <input id="btn-search" type="submit" value="Search" />
                    </form>
                </div>
                <div class="sort">
                    Sort by course code: <br />
                    <input id="1" type="radio" name="sort" checked value="Default" />
                    <label for="1">Default</label><br>
                    <input id="2" type="radio" name="sort" value="A-Z" />
                    <label for="2">A-Z</label><br>
                    <input id="3" type="radio" name="sort" value="Z-A" />
                    <label for="3">Z-A</label><br>
                </div>
            </div>
        </div>
    </div>

    <script>
        var radioBtn = document.querySelectorAll("input[name='sort']");
        radioBtn.forEach(function(curVal){
            curVal.addEventListener('change', function(){
                sort(document.querySelector('input[name="sort"]:checked').value);
            });
        });

        var listCourseDefault = document.querySelectorAll("a.course");
        var listCourseContainer = document.querySelector(".course-container");
        var listCourseForSort = Array.from(document.querySelectorAll('a.course'));

        listCourseForSort.sort((a, b) => {
            let courseCodeA = a.querySelector('.course-code').textContent;
            let courseCodeB = b.querySelector('.course-code').textContent;

            if (courseCodeA < courseCodeB) {
                return -1;
            }
            if (courseCodeA > courseCodeB) {
                return 1;
            }
            return 0;
        });

        var listCourseForSort1 = listCourseForSort.slice();
        listCourseForSort1.reverse();

        function sort(sort_type){
            if(listCourseDefault.length > 0){
                listCourseContainer.innerHTML = "";
                if (sort_type == "Default") {
                    listCourseDefault.forEach(function (curVal) {
                        listCourseContainer.appendChild(curVal);
                    });
                } else if (sort_type == "A-Z") {
                    listCourseForSort.forEach(function (curVal) {
                        listCourseContainer.appendChild(curVal);
                    });
                } else if (sort_type == "Z-A") {
                    listCourseForSort1.forEach(function (curVal) {
                        listCourseContainer.appendChild(curVal);
                    });
                }
            }
        }
    </script>
</body>
</html>